name: Flutter CICD

on:
  push:
    branches:
      - main
      - develop
      - release
  pull_request:
    branches:
      - main
      - develop
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.6"

      - name: Verify Flutter installation
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: formate whole project file code
        run: dart format .

      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze Project
        run: flutter analyze

      #      - name: Run tests
      #        run: flutter test

      #      - name: Build Android App Bundle
      #        run: flutter build appbundle
      #
      #      - name: Upload AAB artifact
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: android-appbundle
      #          path: build/app/outputs/bundle/release/app-release.aab

      #      - name: Install Fastlane dependencies
      #        run: bundle install
      #
      #      - name: Build using Fastlane
      #        run: bundle exec fastlane build

      - name: Install Fastlane
        run: |
          sudo gem install fastlane

      - name: Build with Fastlane
        working-directory: android
        run: fastlane build
